version: '3'

services:
  client:
    image: garystafford/voter-client:rabbitmq-0.4.55
    depends_on:
    - gateway
    hostname: client
    ports:
    - "80:8080/tcp"
    networks:
    - demo_overlay_net

  gateway:
    image: garystafford/voter-api-gateway:kub-aks-0.5.1
    depends_on:
    - election
    - candidate
    - voter
    hostname: voter-api-gateway
    ports:
    - "8080:8080/tcp"
    networks:
    - demo_overlay_net

  election:
    image: garystafford/election-service:kub-aks-0.5.38
    hostname: election
    ports:
    - "8080:8080/tcp"
    command: "java -Dspring.profiles.active=kub-aks \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar election/election-service.jar"
    networks:
    - demo_overlay_net

  candidate:
    image: garystafford/candidate-service:kub-aks-0.5.119
    hostname: candidate
    ports:
    - "8080:8080/tcp"
    command: "java -Dspring.profiles.active=kub-aks \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar candidate/candidate-service.jar"
    networks:
    - demo_overlay_net

  voter:
    image: garystafford/voter-service:kub-aks-0.5.239
    hostname: voter
    ports:
    - "8080:8080/tcp"
    command: "java -Dspring.profiles.active=kub-aks \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar voter/voter-service.jar"
    networks:
    - demo_overlay_net
networks:
  demo_overlay_net: