server:
  port: 8099
spring:
  data:
   mongodb:
     host: localhost
     port: 27017
     database: voters
logging:
 level:
   root: INFO
info:
 java:
   source: ${java.version}
   target: ${java.version}
management:
 info:
   git:
     mode: full
   build:
     enabled: true
services:
  candidate:
    host: localhost
    port: 8097
---
spring:
 profiles: docker-development
 data:
   mongodb:
     host: mongodb
services:
  candidate:
    host: candidate
---
spring:
 profiles: aws-production
 data:
   mongodb:
     host: 10.0.1.6
logging:
 level:
   root: WARN
management:
 info:
   git:
     enabled: false
   build:
     enabled: false
endpoints:
 sensitive: true
 enabled: false
 info:
   enabled: true
 health:
   enabled: true
services:
  candidate:
    host: candidate
---
spring:
 profiles: docker-production
 data:
   mongodb:
     host: mongodb
logging:
 level:
   root: WARN
management:
 info:
   git:
     enabled: false
   build:
     enabled: false
endpoints:
 sensitive: true
 enabled: false
 info:
   enabled: true
 health:
   enabled: true
services:
  candidate:
    host: candidate
